[tool.ruff]
line-length = 100
lint.select = ["E","F","I","B","UP","ISC","W","N"]
[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
disallow_untyped_defs = true
ignore_missing_imports = true
